# Generated by Django 4.2.4 on 2023-08-15 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 22, 37, 58, 444614, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 15, 22, 38, 23, 598648, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
