# Generated by Django 4.2.4 on 2023-08-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_booking_booking_date_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='none@littlelemon.com', max_length=254),
            preserve_default=False,
        ),
    ]
