# Generated by Django 4.2.4 on 2023-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='no description', max_length=2000),
            preserve_default=False,
        ),
    ]
